### ISSUE TITLE
Update & test Panflute 2 with Pandoc 2.11

### ISSUE THREAD

**Issue by noelmace** [noelmace/pandoc-import-code#1]
As panflute does not support Pandoc 2.10 yet, we can't either.
Therefore, when using Pandoc 2.10, some users may run into an `unknown tag` error, especially if tables are used.

Here is an example:

```
Traceback (most recent call last):
  File "/home/noel/.local/bin/pandoc-import-code", line 8, in <module>
    sys.exit(main())
  File "/home/noel/.local/lib/python3.8/site-packages/pandoc_import_code.py", line 162, in main
    return pf.run_filter(action, doc=doc)
  File "/home/noel/.local/lib/python3.8/site-packages/panflute-1.12.5-py3.8.egg/panflute/io.py", line 266, in run_filter
  File "/home/noel/.local/lib/python3.8/site-packages/panflute-1.12.5-py3.8.egg/panflute/io.py", line 239, in run_filters
  File "/home/noel/.local/lib/python3.8/site-packages/panflute-1.12.5-py3.8.egg/panflute/io.py", line 59, in load
    OpenWrapper = _io.open # for compatibility with _pyio
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/noel/.local/lib/python3.8/site-packages/panflute-1.12.5-py3.8.egg/panflute/elements.py", line 1532, in from_json
Exception: unknown tag: Caption
Error running filter pandoc-import-code:
Filter returned error status 1
```

This issue should solve by itself as soon as https://github.com/sergiocorreia/panflute/issues/142 is closed.

**Comment by noelmace** [comment]
See https://github.com/sergiocorreia/panflute/releases/tag/2.0.3
